// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSb1kwcJFT5p9_0o_3E_HxqCh9oPLcXjs',
    appId: '1:1017330362180:web:067ed062d57461a38a9911',
    messagingSenderId: '1017330362180',
    projectId: 'chat-app-befe4',
    authDomain: 'chat-app-befe4.firebaseapp.com',
    storageBucket: 'chat-app-befe4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQi7qKqdY8hKQL9ZhtHoVnfMZNCwOXc1E',
    appId: '1:1017330362180:android:5f076d268b4bc0ee8a9911',
    messagingSenderId: '1017330362180',
    projectId: 'chat-app-befe4',
    storageBucket: 'chat-app-befe4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTqQOIwYh7LJCEglUp_VlwwV1weJ5-Zrs',
    appId: '1:1017330362180:ios:38106f4b108dea058a9911',
    messagingSenderId: '1017330362180',
    projectId: 'chat-app-befe4',
    storageBucket: 'chat-app-befe4.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSb1kwcJFT5p9_0o_3E_HxqCh9oPLcXjs',
    appId: '1:1017330362180:web:5a99309ea6a7050a8a9911',
    messagingSenderId: '1017330362180',
    projectId: 'chat-app-befe4',
    authDomain: 'chat-app-befe4.firebaseapp.com',
    storageBucket: 'chat-app-befe4.appspot.com',
  );
}
